apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-demo-ingress
spec:
  defaultBackend:
    service:
      name: {{ .Values.service.name  | quote }}
      port:
        number: {{ .Values.service.port }}
---